/* Auto-generated by utensor cli */
#ifndef __MY_MODEL_H
#define __MY_MODEL_H

#include "uTensor/core/tensor.hpp"

constexpr uint16_t estimated_ram_usage = 4440;
constexpr uint16_t estimated_meta_usage = 960;

void compute_my_model(uTensor::Tensor& t_input_10, uTensor::Tensor& t_Identity0);

#endif // __MY_MODEL_H