/* Auto-generated by utensor cli */
#ifndef __MY_MODEL_INTERFACE_H
#define __MY_MODEL_INTERFACE_H
#include "uTensor.h"

using namespace uTensor;

class My_model : public ModelInterface<1, 1> 
{
 public:
  enum input_names : uint8_t { input_0 };
  enum output_names : uint8_t { output_0 };
  My_model();
 protected:
  virtual void compute();
 private:
  // Operators
  ReferenceOperators::ReshapeOperator<int8_t> op_ReshapeOperator_000;

  ReferenceOperators::MaxPoolOperator<int8_t> op_MaxPoolOperator_001;

  TflmSymQuantOps::DequantizeOperator<float, int8_t> op_DequantizeOperator_002;

  TflmSymQuantOps::FullyConnectedOperator<int8_t> op_FullyConnectedOperator_003;

  TflmSymQuantOps::DepthwiseSeparableConvOperator<int8_t> op_DepthwiseSeparableConvOperator_004;

  TflmSymQuantOps::FullyConnectedOperator<int8_t> op_FullyConnectedOperator_005;

  TflmSymQuantOps::QuantizeOperator<int8_t, float> op_QuantizeOperator_006;

  // memory allocators
  localCircularArenaAllocator<4440, uint16_t> ram_allocator;
  localCircularArenaAllocator<960, uint16_t> metadata_allocator;
};

#endif // __MY_MODEL_INTERFACE_H